refactoring/CSS layoutcss를 styled component에서 tailewind변경
gnims-project/Gnims-frontend pull request #215
Opened 2023-04-14 03:51 UTC by haruharuganda

refactoring/CSS layoutcss를 styled component에서 tailewind변경

2023-04-14 03:53 UTC, AngelaChaejung approved these changes

2023-04-19 00:51 UTC, dong-fa requested changes

2023-04-19 00:51 UTC, dong-fa commented on src/shared/AxiosInstance.jsx
> +  baseURL: "https://eb.jxxhxxx.shop",
여기 환경 변수 설정 변경 해주세요

2023-04-19 04:41 UTC, AngelaChaejung commented on src/shared/AxiosInstance.jsx
> +  baseURL: "https://eb.jxxhxxx.shop",
다시 환경변수이용하는걸로 수정했어요!

2023-04-19 04:54 UTC, dong-fa approved these changes

2023-04-19 04:54 UTC, merged